name = "fcsp++"
author = "scotus*"
version = "v0.2.0b-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f380069e78b97c662d12e1407072d4613b3b9b774cdab8cdfc22ac4c7a886987"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
