name = "hotpot"
author = "scotus*"
version = "v1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "305435943ec151f7993fbb79e3c3b127babe4bb93952086444725d50367c9d69"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
