name = "fcsp"
author = "scotus*"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ae764168c9996fb9f9ece1a63d2ca6bacf4b8feb4e026bcabc8d1d77ac5df1a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
