name = "fcsp - client side"
author = "scotus*"
version = "1.0.4c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13552a763f6b21827bf71f1a684c1782fc9827adadc45bb4b5d7bf4284b8fd9d"

[versions]
minecraft = "1.20.1"
quilt = "0.23.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
