name = "fcsp"
author = "scotus*"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59a32cd631f8082c81197c3f26c0782f7ca6ed293c659dccdca843a0d2166db5"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
