name = "fcsp - client side"
author = "scotus*"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ec7825afcb090c8c0f31259092677acb063789428cfbe4897ebe72b8df5d9d7"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
