name = "fcsp++"
author = "scotus*"
version = "v0.1.0b-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3286e7630406182bf0832d8f585aaffae7a7d4cc6a6f65e4c10c4ecb1398f6bf"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
