name = "fcsp++"
author = "scotus*"
version = "v0.4.1b-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b2e2442b637ad1948549232f4ce2883f3cc2f7ee9e7efca38838770ed59aca6"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0-beta.4"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
