name = "fcsp++"
author = "scotus*"
version = "v0.2.0b-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf0302cc926cb114e63c22d8721dfc1004c39ce9ce17e75b3f73e7e7704083f3"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
