name = "fcsp++"
author = "scotus*"
version = "v0.3.0b-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea74ef372b2d72809dfae7d9e266a3a43fb7e44ae4a767858de44c1a9c017048"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
