name = "fcsp+-"
author = "scotus-1"
version = "0.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b75a3b861eb3fd823171cc4bcf389784c7747caca68ebfd552f5205fba7ec4a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
