name = "fcsp+-"
author = "scotus-1"
version = "0.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1ef73eab80d59d11c4ba1ef1b2954d54bdd4e754b2246fe02417365b2fd8c4a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
