name = "fcsp+-"
author = "scotus-1"
version = "0.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d68ce1882dff5ab7b978ff5aa59f38a73200c00354ef44a38943d3f3e127e6a8"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
