name = "fcsp+-"
author = "scotus-1"
version = "0.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40bbf683101028e69a82de9536abe87868914544c3186e7e5b7f3be9235df88d"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"
